### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Vilin97** [Vilin97/TelegramAIbot#1]
- [x] Russian English toggle 
- [x] Delete messages 
- [ ] Edit messages
- [ ] RAG and/or summaries 
- [ ] Fine tune on DND data, like DND rule book 
- [ ] Voice
- [ ] Pre-generate the world, don't tell the user 
- [ ] Map support?
